/** Bony Polymers — KRA/KPI Master Sheet reference data */

import { IT_KPIS } from "@/lib/it-kpis";

export const PLANT_UNIT = "Bony Polymers" as const;
/** Internal DB tag only — not shown in UI */
export const FISCAL_YEAR = "" as const;

export const RATING_SCALE = [
  { rating: "A+", category: "Outstanding", meaning: "Exceptional performance; far exceeds all KPIs; role model" },
  { rating: "A", category: "Excellent", meaning: "Exceeds targets consistently; strong contributor" },
  { rating: "B+", category: "Good", meaning: "Meets targets with some above-average contributions" },
  { rating: "B", category: "Average", meaning: "Meets basic expectations; scope for improvement" },
  { rating: "C", category: "Below Average", meaning: "Misses key targets; needs improvement plan" },
  { rating: "D", category: "Poor", meaning: "Consistently underperforms; immediate action required" },
] as const;

export const PERSPECTIVES = ["Finance", "Quality", "Process"] as const;

export type QuarterTargets = {
  q1: { target: string; achieved?: string };
  q2: { target: string; achieved?: string };
  q3: { target: string; achieved?: string };
  q4: { target: string; achieved?: string };
};

export type PlantKpiDef = {
  id: string;
  kraName: string;
  name: string;
  category: string;
  perspective?: string;
  unit: string;
  weightage: number;
  targetValue: number;
  direction: "HIGHER_IS_BETTER" | "LOWER_IS_BETTER";
  department: string;
  kpiLevel: "PLANT" | "DEPARTMENT" | "INDIVIDUAL";
  ownerName?: string;
  fiscalYear?: string;
  plantUnit?: string;
  quarterTargets: QuarterTargets;
  values?: number[];
};

function q(all: string, achieved?: Partial<Record<"q1" | "q2" | "q3" | "q4", string>>): QuarterTargets {
  return {
    q1: { target: all, achieved: achieved?.q1 ?? "" },
    q2: { target: all, achieved: achieved?.q2 ?? "" },
    q3: { target: all, achieved: achieved?.q3 ?? "" },
    q4: { target: all, achieved: achieved?.q4 ?? "" },
  };
}

/** Plant Head — KRA / KPI Master Sheet */
export const PLANT_LEVEL_KPIS: PlantKpiDef[] = [
  {
    id: "37p-sales-target",
    kraName: "Sales Target (₹ Cr)",
    name: "Revenue vs Budget",
    category: "Sales",
    unit: "₹ Cr",
    weightage: 0.2,
    targetValue: 150.18,
    direction: "HIGHER_IS_BETTER",
    department: "Plant Head",
    kpiLevel: "PLANT",
    quarterTargets: {
      q1: { target: "27.29", achieved: "" },
      q2: { target: "35.37", achieved: "0" },
      q3: { target: "42.16", achieved: "0" },
      q4: { target: "45.36", achieved: "0" },
    },
    values: [24.5, 26.1, 27.29, 28.0, 30.2, 32.1],
  },
  {
    id: "37p-otd",
    kraName: "Delivery Adherence (%)",
    name: "On-Time Delivery (OTD %)",
    category: "Sales",
    unit: "%",
    weightage: 0.1,
    targetValue: 99.95,
    direction: "HIGHER_IS_BETTER",
    department: "Plant Head",
    kpiLevel: "PLANT",
    quarterTargets: {
      q1: { target: "95%", achieved: "0" },
      q2: { target: "97%", achieved: "0" },
      q3: { target: "98%", achieved: "0" },
      q4: { target: "98%", achieved: "0" },
    },
    values: [92, 93, 94, 95, 96, 96],
  },
  {
    id: "37p-rejection",
    kraName: "Quality (Plant Rejection %)",
    name: "Plant Rejection %",
    category: "Quality",
    unit: "%",
    weightage: 0.15,
    targetValue: 8.75,
    direction: "LOWER_IS_BETTER",
    department: "Quality",
    kpiLevel: "PLANT",
    quarterTargets: {
      q1: { target: ">9%", achieved: "0" },
      q2: { target: ">9%", achieved: "0" },
      q3: { target: ">8%", achieved: "0" },
      q4: { target: ">7%", achieved: "0" },
    },
    values: [11, 10.5, 10, 9.8, 9.5, 9.2],
  },
  {
    id: "37p-inventory",
    kraName: "Inventory (Turns / Days)",
    name: "Inventory Turns / Days",
    category: "Finance",
    unit: "days",
    weightage: 0.1,
    targetValue: 7,
    direction: "LOWER_IS_BETTER",
    department: "Store",
    kpiLevel: "PLANT",
    quarterTargets: q("7 days"),
    values: [9, 8.5, 8, 7.5, 7.2, 7],
  },
  {
    id: "37p-ebitda",
    kraName: "Profitability",
    name: "EBITDA %",
    category: "Finance",
    unit: "%",
    weightage: 0.1,
    targetValue: 11,
    direction: "HIGHER_IS_BETTER",
    department: "Finance",
    kpiLevel: "PLANT",
    quarterTargets: {
      q1: { target: "9%", achieved: "" },
      q2: { target: "10%", achieved: "" },
      q3: { target: "11%", achieved: "" },
      q4: { target: "12%", achieved: "" },
    },
    values: [8.2, 8.5, 9, 9.2, 9.8, 10.1],
  },
  {
    id: "37p-5s",
    kraName: "Operational Excellence",
    name: "5S Audit Score",
    category: "Process",
    unit: "score",
    weightage: 0.2,
    targetValue: 0.92,
    direction: "HIGHER_IS_BETTER",
    department: "All Departments",
    kpiLevel: "PLANT",
    quarterTargets: {
      q1: { target: "0.9", achieved: "" },
      q2: { target: "0.9", achieved: "" },
      q3: { target: "0.92", achieved: "" },
      q4: { target: "0.95", achieved: "" },
    },
    values: [0.82, 0.84, 0.86, 0.88, 0.89, 0.9],
  },
  {
    id: "37p-npd",
    kraName: "New Product Development",
    name: "No. of Successful SOPs",
    category: "Production",
    unit: "nos",
    weightage: 0.1,
    targetValue: 4,
    direction: "HIGHER_IS_BETTER",
    department: "Production",
    kpiLevel: "PLANT",
    quarterTargets: q("1 per quarter"),
    values: [0, 1, 1, 2, 2, 3],
  },
  {
    id: "37p-lti",
    kraName: "Safety: Lost Time Injury, Zero Accident",
    name: "Lost Time Injury (LTI)",
    category: "Safety",
    unit: "count",
    weightage: 0.05,
    targetValue: 0,
    direction: "LOWER_IS_BETTER",
    department: "Safety",
    kpiLevel: "PLANT",
    quarterTargets: q("Zero"),
    values: [0, 0, 0, 0, 0, 0],
  },
];

/** Production department KPIs */
export const PRODUCTION_KPIS: PlantKpiDef[] = [
  {
    id: "37p-prod-achievement",
    kraName: "Production Achievement (%)",
    name: "Plan vs Actual",
    category: "Production",
    unit: "%",
    weightage: 0.2,
    targetValue: 100,
    direction: "HIGHER_IS_BETTER",
    department: "Production",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("As per plan"),
    values: [92, 94, 95, 96, 97, 98],
  },
  {
    id: "37p-prod-otd",
    kraName: "Customer Delivery (%)",
    name: "OTD",
    category: "Sales",
    unit: "%",
    weightage: 0.2,
    targetValue: 100,
    direction: "HIGHER_IS_BETTER",
    department: "Production",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("100%"),
    values: [94, 95, 96, 97, 97, 98],
  },
  {
    id: "37p-prod-ppm",
    kraName: "Quality (PPM / Rejection %)",
    name: "Customer PPM / Rejection %",
    category: "Quality",
    unit: "PPM",
    weightage: 0.15,
    targetValue: 20,
    direction: "LOWER_IS_BETTER",
    department: "Production",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("20 PPM"),
    values: [35, 32, 28, 25, 22, 20],
  },
  {
    id: "37p-prod-oee",
    kraName: "Productivity",
    name: "OEE Improvement",
    category: "Production",
    unit: "%",
    weightage: 0.1,
    targetValue: 85,
    direction: "HIGHER_IS_BETTER",
    department: "Production",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("Improve YoY"),
    values: [72, 74, 76, 78, 80, 82],
  },
];

/** QA department */
export const QA_KPIS: PlantKpiDef[] = [
  {
    id: "37p-qa-ppm",
    kraName: "Ensure zero-defect quality and customer satisfaction",
    name: "Customer PPM (Parts Per Million)",
    category: "Quality",
    unit: "PPM",
    weightage: 0.3,
    targetValue: 50,
    direction: "LOWER_IS_BETTER",
    department: "Quality Assurance",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q(">50% all Customer"),
    values: [80, 70, 65, 58, 52, 48],
  },
  {
    id: "37p-qa-a-rank",
    kraName: "Ensure zero-defect quality and customer satisfaction",
    name: "No A Rank Quality Problem",
    category: "Quality",
    unit: "count",
    weightage: 0.2,
    targetValue: 0,
    direction: "LOWER_IS_BETTER",
    department: "Quality Assurance",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("Zero"),
    values: [2, 1, 1, 0, 0, 0],
  },
  {
    id: "37p-qa-complaints",
    kraName: "Customer Complaint Management",
    name: "Number of customer complaints",
    category: "Quality",
    unit: "nos",
    weightage: 0.15,
    targetValue: 8,
    direction: "LOWER_IS_BETTER",
    department: "Quality Assurance",
    kpiLevel: "DEPARTMENT",
    quarterTargets: {
      q1: { target: "3", achieved: "0" },
      q2: { target: "3", achieved: "0" },
      q3: { target: "1", achieved: "0" },
      q4: { target: "1", achieved: "0" },
    },
    values: [17, 14, 12, 10, 9, 8],
  },
  {
    id: "37p-qa-tat",
    kraName: "Customer Complaint Management",
    name: "Complaint closure TAT",
    category: "Quality",
    unit: "days",
    weightage: 0.1,
    targetValue: 3,
    direction: "LOWER_IS_BETTER",
    department: "Quality Assurance",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("3 days"),
    values: [5, 4.5, 4, 3.5, 3.2, 3],
  },
];

/** Maintenance department */
export const MAINTENANCE_KPIS: PlantKpiDef[] = [
  {
    id: "37p-maint-stoppage",
    kraName: "Line Stoppage",
    name: "Unplanned line stoppages",
    category: "Maintenance",
    unit: "count",
    weightage: 0.2,
    targetValue: 0,
    direction: "LOWER_IS_BETTER",
    department: "Maintenance",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("Zero"),
    values: [3, 2, 2, 1, 1, 0],
  },
  {
    id: "37p-maint-pm",
    kraName: "Preventive Maintenance",
    name: "PM schedule adherence",
    category: "Maintenance",
    unit: "%",
    weightage: 0.2,
    targetValue: 98,
    direction: "HIGHER_IS_BETTER",
    department: "Maintenance",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("98%"),
    values: [92, 93, 94, 95, 96, 97],
  },
  {
    id: "37p-maint-mttr",
    kraName: "MTTR",
    name: "Mean Time to Repair",
    category: "Maintenance",
    unit: "mins",
    weightage: 0.15,
    targetValue: 30,
    direction: "LOWER_IS_BETTER",
    department: "Maintenance",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("30 mins"),
    values: [55, 50, 45, 40, 35, 32],
  },
  {
    id: "37p-maint-mtbf",
    kraName: "MTBF",
    name: "Mean Time Between Failure",
    category: "Maintenance",
    unit: "days",
    weightage: 0.1,
    targetValue: 270,
    direction: "HIGHER_IS_BETTER",
    department: "Maintenance",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("270 Days"),
    values: [180, 200, 220, 240, 255, 265],
  },
];

/** Store — Mr. Praveen Kumar (Parveen Store.xlsx) */
export const STORE_KPIS: PlantKpiDef[] = [
  {
    id: "37p-store-rm-procurement",
    kraName: "Inventory Control & Management",
    name: "On time RM Procurement in line with PPC/Customer schedules",
    category: "Finance",
    perspective: "Finance",
    unit: "%",
    weightage: 0.08,
    targetValue: 100,
    direction: "HIGHER_IS_BETTER",
    department: "Store",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("100%"),
    values: [95, 96, 97, 98, 99, 100],
  },
  {
    id: "37p-store-cost-reduction",
    kraName: "Inventory Control & Management",
    name: "Cost Reduction",
    category: "Finance",
    perspective: "Finance",
    unit: "₹",
    weightage: 0.15,
    targetValue: 10,
    direction: "HIGHER_IS_BETTER",
    department: "Store",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("10% Less"),
    values: [4, 5, 6, 7, 8, 9],
  },
  {
    id: "37p-store-fifo",
    kraName: "Process Excellence",
    name: "Maintain FIFO",
    category: "Process",
    perspective: "Process",
    unit: "%",
    weightage: 0.05,
    targetValue: 100,
    direction: "HIGHER_IS_BETTER",
    department: "Store",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("100% on daily"),
    values: [92, 94, 96, 97, 98, 100],
  },
  {
    id: "37p-store-5s",
    kraName: "Process Excellence",
    name: "Store 5S",
    category: "Process",
    perspective: "Process",
    unit: "score",
    weightage: 0.08,
    targetValue: 0.8,
    direction: "HIGHER_IS_BETTER",
    department: "Store",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("0.8"),
    values: [0.65, 0.68, 0.72, 0.75, 0.78, 0.8],
  },
  {
    id: "37p-store-grn",
    kraName: "Process Excellence",
    name: "GRN (Goods Receipt Note) Maintain",
    category: "Process",
    perspective: "Process",
    unit: "%",
    weightage: 0.05,
    targetValue: 100,
    direction: "HIGHER_IS_BETTER",
    department: "Store",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("100%"),
    values: [90, 92, 94, 96, 98, 100],
  },
];

/** Billing — Ms. Sudha Jetli (Sudha.xlsx) */
export const BILLING_KPIS: PlantKpiDef[] = [
  {
    id: "37p-billing-invoicing",
    kraName: "Customer Satisfaction",
    name: "100% accurate invoicing",
    category: "Quality",
    perspective: "Quality",
    unit: "%",
    weightage: 0.1,
    targetValue: 100,
    direction: "HIGHER_IS_BETTER",
    department: "Billing",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("100%"),
    values: [96, 97, 98, 99, 99, 100],
  },
  {
    id: "37p-billing-sap",
    kraName: "Process Excellence",
    name: "SAP - Sales Order Punching (as per rates agreed)",
    category: "Process",
    perspective: "Process",
    unit: "%",
    weightage: 0.15,
    targetValue: 100,
    direction: "HIGHER_IS_BETTER",
    department: "Billing",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("100% as per customer schedules"),
    values: [94, 95, 96, 97, 98, 99],
  },
  {
    id: "37p-billing-schedule",
    kraName: "Process Excellence",
    name: "Billing as per Customer Schedule, PO & Govt. Norms",
    category: "Process",
    perspective: "Process",
    unit: "%",
    weightage: 0.25,
    targetValue: 100,
    direction: "HIGHER_IS_BETTER",
    department: "Billing",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("100%"),
    values: [92, 94, 95, 96, 98, 99],
  },
  {
    id: "37p-billing-portal",
    kraName: "Process Excellence",
    name: "Update on Customer Portals",
    category: "Process",
    perspective: "Process",
    unit: "%",
    weightage: 0.2,
    targetValue: 100,
    direction: "HIGHER_IS_BETTER",
    department: "Billing",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("100% adherence"),
    values: [90, 92, 94, 96, 98, 100],
  },
  {
    id: "37p-billing-5s",
    kraName: "Process Excellence",
    name: "Office 5S Maintain",
    category: "Process",
    perspective: "Process",
    unit: "score",
    weightage: 0.05,
    targetValue: 0.95,
    direction: "HIGHER_IS_BETTER",
    department: "Billing",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("0.95"),
    values: [0.82, 0.85, 0.88, 0.9, 0.92, 0.95],
  },
  {
    id: "37p-billing-mahima-entry",
    kraName: "Process Excellence",
    name: "Accurate billing data entry (DEO)",
    category: "Quality",
    perspective: "Quality",
    unit: "%",
    weightage: 0.2,
    targetValue: 100,
    direction: "HIGHER_IS_BETTER",
    department: "Billing",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("100%"),
    values: [93, 94, 96, 97, 98, 99],
  },
  {
    id: "37p-billing-mahima-docs",
    kraName: "Process Excellence",
    name: "Supporting documents filed on time",
    category: "Process",
    perspective: "Process",
    unit: "%",
    weightage: 0.15,
    targetValue: 100,
    direction: "HIGHER_IS_BETTER",
    department: "Billing",
    kpiLevel: "DEPARTMENT",
    quarterTargets: q("100%"),
    values: [91, 93, 94, 96, 97, 100],
  },
];

/** All department KRA sheets — Bony Polymers (no unit/year in labels) */
export const KRA_SHEETS = [
  { id: "plant", label: "Plant Head", kpis: PLANT_LEVEL_KPIS },
  { id: "production", label: "Production", kpis: PRODUCTION_KPIS },
  { id: "qa", label: "Quality Assurance", kpis: QA_KPIS },
  { id: "maintenance", label: "Maintenance", kpis: MAINTENANCE_KPIS },
  { id: "store", label: "Store", kpis: STORE_KPIS },
  { id: "billing", label: "Billing", kpis: BILLING_KPIS },
  { id: "it", label: "IT", kpis: IT_KPIS },
] as const;

export const ALL_PLANT_KPIS: PlantKpiDef[] = [
  ...PLANT_LEVEL_KPIS,
  ...PRODUCTION_KPIS,
  ...QA_KPIS,
  ...MAINTENANCE_KPIS,
  ...STORE_KPIS,
  ...BILLING_KPIS,
  ...IT_KPIS,
];

